accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views


urlpatterns = [
    path("login/", views.MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'),name='logout'),
]

earnings_dashboard_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("index/", views.index, name="index"),
    path("earnings/", views.EarningsView.as_view(), name="earnings"),
    path("royalties/", views.RoyaltiesView.as_view(), name="royalties"),
    path("billing/", views.BillingView.as_view(), name="billing"),
    path("reports/", views.ReportsView.as_view(), name="reports"),
    path("", views.index, name="root"),
]

earnings_dashboard_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('earnings_dashboard_app.urls')),
]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earnings_dashboard_app/models.py
from django.db import models
from django.contrib.auth.models import User


class ServiceEntity(models.Model):
    entity_name = models.CharField(max_length=255)
    entity_code = models.CharField(max_length=3)

    class Meta:
        verbose_name_plural = "Service Entities"

    def __str__(self):
        return str(self.entity_name)


class Currency(models.Model):
    code = models.CharField(max_length=3)
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Currencies"

    def __str__(self):
        return "%s - %s" % (self.code, self.name)


class Product(models.Model):
    code = models.CharField(max_length=5)
    name = models.CharField(max_length=255)

    def __str__(self):
        return "%s - %s" % (self.code, self.name)


class UserBalanceAccount(models.Model):

    class Meta:
        unique_together = ('user', 'service_entity', 'currency', 'account_type')

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service_entity = models.ForeignKey(ServiceEntity, on_delete=models.PROTECT)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)
    account_type = models.CharField(
        max_length=2,
        choices=[
            ('AR', 'Accounts Receivable'),
            ('RP', 'Royalties Payable')
        ]
    )

    def __str__(self):
        return "%s-%s-%s|%s|%s" % (
            self.service_entity.entity_code,
            self.account_type,
            str(self.currency.code),
            str(self.id),
            str(self.user.username),
        )

    def balance_displayed(self):
        queryset = self.userbalanceentry_set.all().filter(user_display_status="VS")
        return queryset.aggregate(models.Sum('amount'))['amount__sum']

    def balance_reconciled(self):
        queryset = self.userbalanceentry_set.all().exclude(user_display_status="PN")
        return queryset.aggregate(models.Sum('amount'))['amount__sum']

    def balance_all_entries(self):
        queryset = self.userbalanceentry_set.all()
        return queryset.aggregate(models.Sum('amount'))['amount__sum']


class UserBalanceEntry(models.Model):
    user_balance_account = models.ForeignKey(
        UserBalanceAccount,
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(max_digits=14, decimal_places=2, editable=False, default=0)
    date = models.DateField()
    invoice_ref = models.CharField(null=True, blank=True, max_length=255)
    contract_ref = models.CharField(null=True, blank=True, max_length=255)
    entry_type = models.CharField(
        max_length=3,
        choices=[
            ("ARS", "Billed Service Fee"),
            ("ARP", "Service Fee Payment"),
            ("ARI", "AR Balance Adjustment Increase"),
            ("ARD", "AR Balance Adjustment Decrease"),
            ("RPE", "Net Royalties Payable"),
            ("RPP", "Net Royalty Payment"),
            ("RPI", "RP Balance Adjustment Increase"),
            ("RPD", "RP Balance Adjustment Decrease")
        ],
        editable=False
    )
    entry_detail = models.CharField(max_length=255, null=True, blank=True, editable=False)
    user_display_status = models.CharField(
        max_length=2,
        choices=[
            ("PN", "PENDING - NOT RECONCILED"),
            ("PR", "PENDING - RECONCILED"),
            ("VS", "VISIBLE"),
        ],
        default="PN"
    )

    class Meta:
        verbose_name_plural = "User Balance Ledger"

    def save(self, *args, **kwargs):
        if hasattr(self, 'balanceearningsentry'):
            self.entry_detail = self.balanceearningsentry.product.name
            if self.user_balance_account.account_type == "AR":
                self.entry_type = "ARS"
                self.amount = abs(self.balanceearningsentry.service_fee)
            elif self.user_balance_account.account_type == "RP":
                self.entry_type = "RPE"
                self.amount = (abs(self.balanceearningsentry.total_earnings) -
                                       abs(self.balanceearningsentry.service_fee))
        elif hasattr(self, 'balancepaymententry'):
            if self.user_balance_account.account_type == "AR":
                self.entry_type = "ARP"
                self.entry_detail = "Payment Received - Thank you"
            elif self.user_balance_account.account_type == "RP":
                self.entry_type = "RPP"
                self.entry_detail = "Payment Sent from Royalty Balance"
            self.amount = -abs(self.balancepaymententry.payment_amount)
        elif hasattr(self, 'balanceadjustmententry'):
            self.entry_detail = self.balanceadjustmententry.reason
            if self.balanceadjustmententry.adjustment_type == "INC":
                if self.user_balance_account.account_type == "AR":
                    self.entry_type = "ARI"
                elif self.user_balance_account.account_type == "RP":
                    self.entry_type = "RPI"
                self.amount = abs(self.balanceadjustmententry.adjustment_amount)
            elif self.balanceadjustmententry.adjustment_type == "DEC":
                if self.user_balance_account.account_type == "AR":
                    self.entry_type = "ARD"
                elif self.user_balance_account.account_type == "RP":
                    self.entry_type = "RPD"
                self.amount = -abs(self.balanceadjustmententry.adjustment_amount)
        super(UserBalanceEntry, self).save(*args, **kwargs)


class BalanceEarningsEntryProxyManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(balanceearningsentry__isnull=True)


class BalanceEarningsEntryProxy(UserBalanceEntry):

    objects = BalanceEarningsEntryProxyManager()

    class Meta:
        proxy = True
        verbose_name = "Balance Earnings Entry"
        verbose_name_plural = "Balance Earnings Entries"

    def product(self):
        return self.balanceearningsentry.product

    def total_earnings(self):
        return self.balanceearningsentry.total_earnings

    def incremental_earnings(self):
        return self.balanceearningsentry.incremental_earnings

    def service_fee(self):
        return self.balanceearningsentry.service_fee

    def currency(self):
        return self.user_balance_account.currency.code


class BalancePaymentEntryProxyManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(balancepaymententry__isnull=True)


class BalancePaymentEntryProxy(UserBalanceEntry):
    objects = BalancePaymentEntryProxyManager()

    class Meta:
        proxy = True
        verbose_name = "Balance Payment Entry"
        verbose_name_plural = "Balance Payment Entries"

    def currency(self):
        return self.user_balance_account.currency.code

    def payment_amount(self):
        return self.balancepaymententry.payment_amount


class BalanceAdjustmentEntryProxyManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(balanceadjustmententry__isnull=True)


class BalanceAdjustmentEntryProxy(UserBalanceEntry):
    objects = BalanceAdjustmentEntryProxyManager()

    class Meta:
        proxy = True
        verbose_name = "Balance Adjustment Entry"
        verbose_name_plural = "Balance Adjustment Entries"

    def adjustment_type(self):
        return self.balanceadjustmententry.adjustment_type

    def adjustment_type_display(self):
        return self.balanceadjustmententry.get_adjustment_type_display()

    def reason(self):
        return self.balanceadjustmententry.reason

    def currency(self):
        return self.user_balance_account.currency.code

    def adjustment_amount(self):
        return self.balanceadjustmententry.adjustment_amount


class BalanceEarningsEntry(models.Model):
    balance_entry = models.OneToOneField(UserBalanceEntry, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    total_earnings = models.DecimalField(max_digits=14, decimal_places=2)
    incremental_earnings = models.DecimalField(max_digits=14, decimal_places=2, blank=True)
    service_fee = models.DecimalField(max_digits=14, decimal_places=2)
    fee_type_ref = models.CharField(null=True, blank=True, max_length=255)

    class Meta:
        verbose_name_plural = "Balance Earnings Entries"

    def save(self, *args, **kwargs):
        self.total_earnings = abs(self.total_earnings)
        self.incremental_earnings = abs(self.incremental_earnings)
        self.service_fee = abs(self.service_fee)
        if self.balance_entry.user_balance_account.account_type == "AR":
            self.balance_entry.amount = self.service_fee
        elif self.balance_entry.user_balance_account.account_type == "RP":
            self.balance_entry.amount = self.total_earnings - self.service_fee
        self.balance_entry.save()
        super(BalanceEarningsEntry, self).save(*args, **kwargs)


class BalancePaymentEntry(models.Model):
    balance_entry = models.OneToOneField(
        UserBalanceEntry,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    payment_amount = models.DecimalField(max_digits=14, decimal_places=2)
    bank_custom_name = models.CharField(null=True, blank=True, max_length=255)

    class Meta:
        verbose_name_plural = "Balance Payment Entries"

    def save(self, *args, **kwargs):
        self.payment_amount = abs(self.payment_amount)
        self.balance_entry.amount = -abs(self.payment_amount)
        self.balance_entry.save()
        super(BalancePaymentEntry, self).save(*args, **kwargs)


class BalanceAdjustmentEntry(models.Model):
    balance_entry = models.OneToOneField(
        UserBalanceEntry,
        on_delete=models.CASCADE,
        primary_key=True,
    )

earnings_dashboard_app/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from earnings_dashboard_app.models import (
    BalanceEarningsEntry, UserBalanceEntry, UserReport, UserBalanceAccount)


def index(request):
    return redirect(reverse("earnings"))


class EarningsView(LoginRequiredMixin,ListView):
    login_url = "/accounts/login"
    redirect_field_name = "redirect_to"
    model = BalanceEarningsEntry
    template_name = "earnings_dashboard_app/earnings.html"
    context_object_name = "earnings_entries"
    paginate_by = 20

    def get_queryset(self):
        queryset = BalanceEarningsEntry.objects.filter(
            balance_entry__user_balance_account__user=self.request.user,
            balance_entry__user_display_status="VS"
        ).order_by("-balance_entry__date")
        return queryset


class RoyaltiesView(LoginRequiredMixin, ListView):
    login_url = "/accounts/login"
    redirect_field_name = "redirect_to"
    model = UserBalanceEntry
    template_name = "earnings_dashboard_app/royalties.html"
    context_object_name = "royalty_balance_entries"
    paginate_by = 20
    user_balance_account = None

    def get_user_balance_account(self):
        if not self.user_balance_account:
            account_id = self.request.GET.get('account')
            if account_id:
                self.user_balance_account = UserBalanceAccount.objects.filter(
                    user=self.request.user,
                    account_type="RP",
                    account_id=account_id,
                )
            else:
                self.user_balance_account = UserBalanceAccount.objects.filter(
                    user=self.request.user,
                    account_type="RP"
                ).first()
        return self.user_balance_account

    def get_queryset(self):
        queryset = UserBalanceEntry.objects.filter(
            user_balance_account=self.get_user_balance_account(),
            user_display_status='VS',
        ).order_by("-date")
        return queryset

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        if self.user_balance_account is not None:
            context["current_balance"] = self.user_balance_account.balance_displayed()
        else:
            context["current_balance"] = 0.00
        return context


class BillingView(LoginRequiredMixin, ListView):
    login_url = "/accounts/login"
    redirect_field_name = "redirect_to"
    model = UserBalanceEntry
    template_name = "earnings_dashboard_app/billing.html"
    context_object_name = "billing_balance_entries"
    paginate_by = 20
    user_balance_account = None

    def get_user_balance_account(self):
        if not self.user_balance_account:
            account_id = self.request.GET.get('account')
            if account_id:
                self.user_balance_account = UserBalanceAccount.objects.filter(
                    user=self.request.user,
                    account_type="AP",
                    account_id=account_id,
                )
            else:
                self.user_balance_account = UserBalanceAccount.objects.filter(
                    user=self.request.user,
                    account_type="AR"
                ).first()
        return self.user_balance_account

    def get_queryset(self):
        queryset = UserBalanceEntry.objects.filter(
            user_balance_account=self.get_user_balance_account(),
            user_display_status='VS',
        ).order_by("-date")
        return queryset

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        if self.user_balance_account is not None:
            context["current_balance"] = self.user_balance_account.balance_displayed()
        else:
            context["current_balance"] = 0.00
        return context


class ReportsView(LoginRequiredMixin,ListView):
    login_url = "/accounts/login"
    redirect_field_name = "redirect_to"
    template_name = "earnings_dashboard_app/reports.html"
    model = UserReport
    context_object_name = "user_reports"
    paginate_by = 20

    def get_queryset(self):
        queryset = UserReport.objects.filter(
            user_balance_account__user=self.request.user,
        ).order_by("-date")
        return queryset

earnings_dashboard_app/templates/earnings_dashboard_app/billing.html
{% extends "base.html" %}
{% load humanize %}

{%block content%}
    <div class="p-4">
        <div class="container row p-0">
            <h5>Service Fee Balance Payable: {{ current_balance|intcomma }}</h4>
        </div>
        <div class="container row card p-3">
            <table class="table">
                <thead class="table-primary">
                    <tr>
                        <th>Date</th>
                        <th>Transaction Type</th>
                        <th>Description</th>
                        <th class="text-end">Amount</th>
                        <th class="text-end">Currency</th>
                    </tr>
                </thead>
                <tbody>
                    {% for billing_balance_entry in billing_balance_entries %}
                        <tr>
                            <td>{{ billing_balance_entry.date }}</td>
                            <td>{{ billing_balance_entry.get_entry_type_display }}</td>
                            <td>{{ billing_balance_entry.entry_detail }}</td>
                            <td class="text-end">{{ billing_balance_entry.amount|intcomma }}</td>
                            <td class="text-end">{{ billing_balance_entry.user_balance_account.currency.code }}</td>
                        </tr>
                    {% empty %}
                        <td colspan="5" class="text-center">Nothing to show here yet</td>
                    {% endfor %}
                </tbody>
            </table>
            {% include "earnings_dashboard_app/pagination.html" %}
        </div>
    </div>
{% endblock %}

earnings_dashboard_app/templates/earnings_dashboard_app/earnings.html
{% extends "base.html" %}
{% load humanize %}

{%block content%}
    <div class="p-4">
        <div class="container row p-0">
            <h5>Your Earnings</h5>
        </div>
        <div class="container row card p-3">
            <table class="table">
                <thead class="table-primary">
                    <tr>
                        <th>Period Ending</th>
                        <th>Source</th>
                        <th class="text-end">Total Earnings</th>
                        <th class="text-end">Incremental Uplift</th>
                        <th class="text-end">Service Fee</th>
                        <th class="text-end">Currency</th>
                    </tr>
                </thead>
                <tbody>
                    {% for earnings_entry in earnings_entries %}
                        <tr>
                            <td>{{ earnings_entry.balance_entry.date }}</td>
                            <td>{{ earnings_entry.product.name }}</td>
                            <td class="text-end">{{ earnings_entry.total_earnings|intcomma }}</td>
                            <td class="text-end">{{ earnings_entry.incremental_earnings|intcomma }}</td>
                            <td class="text-end">{{ earnings_entry.service_fee|intcomma }}</td>
                            <td class="text-end">{{ earnings_entry.balance_entry.user_balance_account.currency.code }}</td>
                        </tr>
                    {% empty %}
                        <td colspan="6" class="text-center">Nothing to show here yet</td>
                    {% endfor %}
                </tbody>
            </table>
            {% include "earnings_dashboard_app/pagination.html" %}
        </div>
    </div>
{% endblock %}

earnings_dashboard_app/templates/earnings_dashboard_app/pagination.html
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center mb-0">
      {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Previous</a></li>
      {% endif %}
      <li class="page-item active"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
      {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Next</a></li>
      {% endif %}
  </ul>
</nav>

earnings_dashboard_app/templates/earnings_dashboard_app/reports.html
{% extends "base.html" %}
{% load humanize %}

{%block content%}
    <div class="p-4">
        <div class="container row p-0">
            <h5>Reports & Statements</h5>
        </div>
        <div class="container row card p-3">
            <table class="table">
                <thead class="table-primary">
                    <tr>
                        <th>Period Ending</th>
                        <th>Report Type</th>
                        <th>Description</th>
                        <th>Link</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user_report in user_reports %}
                        <tr>
                            <td>{{ user_report.date }}</td>
                            <td>{{ user_report.report_type }}</td>
                            <td>{{ user_report.description }}</td>
                            <td><a href="{{ user_report.file.url }}" target="_blank">Download</a></td>
                        </tr>
                    {% empty %}
                        <td colspan="4" class="text-center">Nothing to show here yet</td>
                    {% endfor %}
                </tbody>
            </table>
            {% include "earnings_dashboard_app/pagination.html" %}
        </div>
    </div>
{% endblock %}

earnings_dashboard_app/templates/earnings_dashboard_app/royalties.html
{% extends "base.html" %}
{% load humanize %}

{%block content%}
    <div class="p-4">
        <div class="container row p-0">
            <h5>Your Royalty Balance: {{ current_balance|intcomma }}</h5>
        </div>
        <div class="container row card p-3">
            <table class="table">
                <thead class="table-primary">
                    <tr>
                        <th>Date</th>
                        <th>Transaction Type</th>
                        <th>Description</th>
                        <th class="text-end">Net Amount</th>
                        <th class="text-end">Currency</th>
                    </tr>
                </thead>
                <tbody>
                    {% for royalty_balance_entry in royalty_balance_entries %}
                        <tr>
                            <td>{{ royalty_balance_entry.date }}</td>
                            <td>{{ royalty_balance_entry.get_entry_type_display }}</td>
                            <td>{{ royalty_balance_entry.entry_detail }}</td>
                            <td class="text-end">{{ royalty_balance_entry.amount|intcomma }}</td>
                            <td class="text-end">{{ royalty_balance_entry.user_balance_account.currency.code }}</td>
                        </tr>
                    {% empty %}
                        <td colspan="5" class="text-center">Nothing to show here yet</td>
                    {% endfor %}
                </tbody>
            </table>
            {% include "earnings_dashboard_app/pagination.html" %}
        </div>
    </div>
{% endblock %}